[package]
name = "escrow-factory-io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gmeta.workspace = true
gstd = { workspace = true, features = ["debug"] }
escrow-io.workspace = true